services:
  db:
    image: mysql:8.0
    container_name: appagua_db
    command: --default-authentication-plugin=mysql_native_password --skip-log-bin
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: bd_sapam
      # ¡NO definir MYSQL_ROOT_PASSWORD cuando usas MYSQL_ALLOW_EMPTY_PASSWORD!
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      timeout: 5s
      retries: 30

  web:
    build: ./backend
    container_name: appagua_web
    env_file:
      - .env
    environment:
      # Django usará estas credenciales para root
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: sh -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
  mysql_data:
